package cr.ac.uned.estructurasdedatos.proyecto1.gui;

import cr.ac.uned.estructurasdedatos.proyecto1.dominio.Pais;
import cr.ac.uned.estructurasdedatos.proyecto1.logica.Ranking;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase para la pantalla principal.
 * 
 * @author Mayarling Martínez
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
     private Ranking ranking = new Ranking();

    /**
     * Se crea un nuevo objeto de tipo PantallaPrincipal.
     */
    public PantallaPrincipal() {
        initComponents();
        cargarModelo();
    }
    
    /**
     * Método para cargar el modelo de datos de manera dinamica.
     */
    public void cargarModelo(){
        String[] encabezadosDeLaTabla = {"Nombre del país", "Puntos"};
        Pais[] paises = this.ranking.getPaises();
        String[][] datos = new String[paises.length][2];
        DecimalFormat formateadorDecimal = new DecimalFormat("#,###.00");
        for(int i = 0; i < paises.length; i++){
            Pais paisPosicionI = paises[i];
            datos[i][0] = paisPosicionI.getNombre();
            datos[i][1] = formateadorDecimal.format(paisPosicionI.getPuntos());
        }
        this.tablaRanking.setModel(new DefaultTableModel(datos, encabezadosDeLaTabla));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRanking = new javax.swing.JTable();
        etiquetaFifa = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuAgregarPuntos = new javax.swing.JMenuItem();
        menuRankingAleatorio = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking Mundial Femenino FIFA");

        etiquetaTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        etiquetaTitulo.setText("Top 10 de paises en el mundial femenino");

        tablaRanking.setEnabled(false);
        jScrollPane1.setViewportView(tablaRanking);

        etiquetaFifa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        etiquetaFifa.setText("FIFA");

        menuOpciones.setText("Opciones");
        menuOpciones.setToolTipText("Click para ver las opciones de menú");

        menuAgregarPuntos.setText("Agregar puntos");
        menuAgregarPuntos.setToolTipText("click para agregar puntos a un pais");
        menuAgregarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarPuntosActionPerformed(evt);
            }
        });
        menuOpciones.add(menuAgregarPuntos);

        menuRankingAleatorio.setText("Nuevo ranking aleatorio");
        menuRankingAleatorio.setToolTipText("Click para generar un nuevo ranking con valores aleatorios.");
        menuRankingAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRankingAleatorioActionPerformed(evt);
            }
        });
        menuOpciones.add(menuRankingAleatorio);

        menuSalir.setText("Salir");
        menuSalir.setToolTipText("Click para salir del programa");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuSalir);

        barraMenu.add(menuOpciones);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(etiquetaTitulo)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(etiquetaFifa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaFifa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAgregarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarPuntosActionPerformed
        PantallaAdicionDePuntos ventananaAdicionDePuntos = new PantallaAdicionDePuntos(this.ranking, this);
        ventananaAdicionDePuntos.setLocationRelativeTo(this);
        ventananaAdicionDePuntos.setVisible(true);
    }//GEN-LAST:event_menuAgregarPuntosActionPerformed

    private void menuRankingAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRankingAleatorioActionPerformed
        int opcionSeleccionada = JOptionPane.showConfirmDialog(
                this,
                "Esta operación va a borrar y generar un nuevo ranking con valores aleatorios.\r\n"
                        + "¿Está seguro que desea continuar?",
                "ATENCIÓN",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if(opcionSeleccionada == JOptionPane.OK_OPTION){
            this.ranking = new Ranking();
            this.cargarModelo();
        }
    }//GEN-LAST:event_menuRankingAleatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel etiquetaFifa;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAgregarPuntos;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuRankingAleatorio;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable tablaRanking;
    // End of variables declaration//GEN-END:variables
}
